version: 0.2

env:
  variables:
    ARTIFACT_NAME: "C-Build-Test-$CODEBUILD_START_TIME"
phases:
  install:
    commands:
      - apt update
      - apt install --yes software-properties-common
      - add-apt-repository ppa:deadsnakes/ppa
      - add-apt-repository ppa:ubuntu-toolchain-r/test
      - apt update
      - apt install --yes python3.7 python3.7-venv python3.7-dev
      - apt install --yes clang
      - python3.7 -m ensurepip
      - python3.7 -m pip install --upgrade pip
      - apt install --yes --no-install-recommends libwayland-dev libxrandr-dev
      - sysctl vm.mmap_rnd_bits=28
  pre_build:
    commands:
      - echo "Installing CMake"
      - apt install cmake
      - echo "Configuring CMake"
      - cmake .
  build:
    commands:
      - echo "Building the project"
      - make
  post_build:
    commands:
        - echo "Running tests"
        - ctest
artifacts:
  files:
    - '**/*'
  name: $ARTIFACT_NAME
  base-directory: '/tmp/lib'
  discard-paths: yes
