version: 0.2

env:
  variables:
    ARTIFACT_NAME: "C-Build-Test-$CODEBUILD_START_TIME"
phases:
  install:
    commands:
      - apt update
      - apt install -y software-properties-common
      - add-apt-repository ppa:fkrull/deadsnakes
      - add-apt-repository ppa:ubuntu-toolchain-r/test
      - apt update
      - apt install -y python3.7 python3.7-venv python3.7-dev
      - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
      - apt install -y clang
      - python3.7 -m ensurepip
      - python3.7 -m pip install --upgrade pip
      - echo "Installing CMake version 3.17.2"
      - wget https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-Linux-x86_64.sh
      - chmod +x cmake-3.17.2-Linux-x86_64.sh --skip-license --prefix=/usr/local
  pre_build:
    commands:
      - echo "Configuring CMake"
      - cmake .
  build:
    commands:
      - echo "Building the project"
      - make
  post_build:
    commands:
        - echo "Running tests"
        - ctest
artifacts:
  files:
    - '**/*'
  name: $ARTIFACT_NAME
  base-directory: '/tmp/lib'
  discard-paths: yes
