steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y cmake && \
        cmake . && \
        make && \
        ctest

artifacts:
  objects:
    location: 'gs://test-ooc/${_ARTIFACT_NAME}/'
    paths:
      - '/tmp/lib/**'
    
substitutions:
  _ARTIFACT_NAME: 'C-Build-Test-$BUILD_ID'


# This section is to specify artifacts to be stored
artifacts:
  objects:
    location: 'gs://test-ooc/${_ARTIFACT_NAME}/'
    paths:
      - '/tmp/lib/**'
    
# Substitutions
substitutions:
  _ARTIFACT_NAME: 'C-Build-Test-$BUILD_ID'
